noun_object = ['car', 'cat', 'house', 'tree', 'dog', 'robot', 'dress', 'window', 'book', 'suit', 'clothes', 'building', 'lion', 'orange', 'bird', 'grass', 'bed', 'door', 'horse', 'ship', 'computer', 'spaceship', 'rabbit', 'ball', 'sword', 'fish', 'castle', 'glasses', 'flower', 'train', 'shirt', 'guitar', 'phone', 'bear', 'motorcycle', 'rock', 'chair', 'boat', 'monkey', 'desk', 'mirror', 'statue', 'fox', 'cup', 'wolf', 'tv', 'jacket', 'bottle', 'apple', 'box', 'plane', 'football', 'butterfly', 'stop sign', 'sunglasses', 'clock', 'palace', 'vehicle', 'skyscrapers', 'pig', 'bus', 'panda', 'rocket', 'elephant', 'traffic light', 'pizza', 'Lily', 'squirrel', 'shark', 'bike', 'hospital', 'frog', 'spider', 'deer', 'cow', 'iris', 'bag', 'owl', 'piano', 'church', 'cake', 'restaurant', 'truck', 'fireplace', 'candles', 'plate', 'spacecraft', 'jeans', 'basketball', 'bowl', 'bench', 'eagle', 'banana', 'tank', 'wine glass', 'knife', 't-shirt', 'airplane', 'laptop', 'dinosaur', 'crow', 'shorts', 'sofa', 'goat', 'bicycle', 'toilet', 'gate', 'duck', 'key', 'lamp', 'kitten', 'leaf', 'boots', 'backpack', 'peacock', 'roses', 'ants', 'umbrella', 'fireflies', 'sheep', 'bow', 'diamond', 'helicopter', 'balloon', 'sculpture', 'bee', 'parrot', 'crab', 'baseball', 'baseball glove', 'baseball bat', 'pencil', 'keyboard', 'gorilla', 'carpet', 'vines', 'basket', 'lotus', 'corn', 'couch', 'jellyfish', 'tennis ball', 'tent', 'lanterns', 'hamburger', 'penguin', 'giraffe', 'tie', 'sweater', 'blanket', 'gloves', 'skateboard', 'carrot', 'aircraft', 'camel', 'scarf', 'parking meter', 'dolphin', 'peach', 'watermelon', 'pumpkin', 'suitcase', 'fence', 'taxi', 'sandwich', 'surfboard', 'strawberry', 'notebook', 'vase', 'dining table', 'curtain', 'kite', 'submarine', 'pigeon', 'puppy', 'sparrow', 'donut', 'seagulls', 'cookie', 'spoon', 'marble', 'earrings', 'cottages', 'stove', 'swan', 'tractor', 'pillow', 'penguins', 'farmhouse', 'hot dog', 'cell phone', 'kangaroo', 'bathtub', 'fork', 'sink', 'teddy bear', 'chick', 'oven', 'bin', 'scissors', 'broccoli', 'llama', 'briefcase', 'towel', 'handbag', 'racoon', 'refrigerator', 'microwave', 'canoe', 'beetle', 'toothbrush', 'goose', 'chandelier', 'fire hydrant', 'tennis racket', 'flamingo', 'toaster', 'snowboard', 'stool', 'skis', 'frisbee', 'remote', 'cushion', 'hair drier', 'potted plant']     

noun_person = ['girl', 'person', 'baby', 'lady', 'king', 'mother', 'princess', 'soldier', 'son', 'father', 'doctor', 'teacher', 'cowboy', 'batman', 'pirate', 'wife', 'dancer', 'prince', 'parents', 'daughter', 'dj', 'singer', 'brother', 'runner', 'chef', 'president', 'grandmother', 'husband', 'sister', 'captain', 'actor', 'grandfather', 'bride', 'actress', 'toddler']

color_attribute = ['black', 'white', 'red', 'green', 'blue', 'golden', 'yellow', 'pink', 'orange', 'brown', 'purple', 'gray', 'grey', 'silver']

shape_attribute = ['square', 'circular', 'cube', 'triangular', 'spiral', 'triangle', 'sphere', 'heart-shaped', 'round', 'pentagram', 'disc-shaped', 'cubic', 'crescent', 'star-shaped', 'octagonal', 'oblong', 'pentagonal', 'annular', 'crescent-shaped', 'cube-shaped', 'fan-shaped', 'spheric', 'ring-shaped', 'L-shaped', 'S-shaped', 'cuboid']       

texture_attribute = ['wooden', 'paper', 'leather', 'wood', 'fur', 'metallic', 'rubber', 'bamboo', 'lava', 'cotton', 'clay', 'feather', 'ceramic', 'marble', 'parchment', 'cardboard', 'metal', 'Wicker', 'woven', 'woolen', 'knitted', 'spongy', 'plushy', 'rubbery', 'leathery', 'lacier']          

verb = ['walking', 'wearing', 'flying', 'moving', 'dancing', 'running', 'standing', 'playing', 'detailed', 'talking', 'floating', 'eating', 'falling', 'smiling', 'riding', 'driving', 'flowing', 'going', 'casting', 'drawing', 'taking', 'laughing', 'jumping', 'emphasizing', 'turning', 'reflecting', 'highlighting', 'singing', 'drinking', 'burning', 'blowing', 'swimming', 'symbolizing', 'waving', 'come', 'pass', 'painting', 'lying', 'convey', 'rolling', 'spinning', 'rotating', 'chasing', 'swirling', 'sparkling', 'bathed', 'haunted', 'leaves', 'nestled', 'crashing', 'dripping', 'swaying', 'flickering', 'give', 'throwing', 'climbing', 'reflects', 'fixed', 'traveling', 'hitting', 'approaching', 'crossing', 'cutting', 'blending', 'sailing', 'pointing', 'typing', 'Illustrate', 'soaring', 'rises', 'surfing', 'emitting', 'teaching', 'cooking', 'fluttering', 'raised', 'pulling', 'bouncing', 'navigating', 'discussing', 'pushing', 'washing', 'diving', 'escape', 'marching', 'punching', 'explaining', 'interacting', 'asking', 'cascading', 'descend', 'rushing', 'kicking', 'cleaning', 'looping', 'sending', 'chatting', 'whispering', 'sliding', 'orbiting', 'sipping', 'shake', 'flipping', 'strolling', 'feeding', 'tearing', 'carved', 'elongated', 'billowing', 'stumbled', 'mixing', 'hopping', 'introduce', 'dining', 'skating', 'winking', 'trembling', 'crafting', 'smashing', 'galloping', 'wagging', 'glide', 'sucking', 'fleeing', 'sneaking', 'ripping', 'grazing', 'submerged', 'skateboarding', 'polished', 'twirling', 'sliced', 'tapping', 'clashing', 'spiraling', 'chopping', 'sculpted', 'revolving', 'knitted', 'traversing', 'repairing', 'dragging', 'skydiving', 'craft', 'rippling', 'stirring', 'sprinting', 'cruising', 'shaved', 'darting', 'shivering', 'strides', 'breathe', 'wiggling', 'tumbling', 'surging', 'sled', 'rowing', 'accompany', 'dashing', 'dust', 'plucking', 'trimmed', 'snowboarding', 'escalating', 'grasp', 'propelling', 'tossed', 'scurrying', 'trekking', 'circle', 'paddling', 'intimate', 'strutting', 'paced', 'flit', 'wading', 'trembled', 'entertain', 'gossiping', 'mocking', 'fleeting', 'pedaling', 'swoops', 'vacuuming', 'trotting', 'skidding', 'escorted', 'jiggling', 'wiggles', 'touring', 'skimming', 'plummets', 'disinfecting', 'scampering', 'boating', 'hauling', 'waddle', 'rinsing', 'yacht']
